version: "3.8"
services:
  app:
    image: url-shorter:latest
    ports:
      - "3001:3000"
    depends_on:
      - redis
      - process-queue
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PROCESS_QUEUE_URL: http://process-queue:3000
    networks:
      - my-network-overlay
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my-network-overlay
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network-overlay
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1024M"

  process-queue:
    image: process-queue:latest
    networks:
      - my-network-overlay
    environment:
      MONGO_URI: mongodb://mongodb:27017/nest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  my-network-overlay:
    driver: overlay

volumes:
  mongo_data:
