version: "3.8"
services:
  app:
    image: url-shorter:latest # Utiliza la imagen construida
    ports:
      - "3001:3000"
    depends_on:
      - redis
      - process-queue
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PROCESS_QUEUE_URL: http://process-queue:3000
    networks:
      - my-network-overlay
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my-network-overlay

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network-overlay

  process-queue:
    image: process-queue:latest # Utiliza la imagen construida
    networks:
      - my-network-overlay
    environment:
      MONGO_URI: mongodb://mongodb:27017/nest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
      restart_policy:
        condition: on-failure

networks:
  my-network-overlay:
    driver: overlay

volumes:
  mongo_data:
